# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          github-actions:
              patterns:
                  - '*'
      cooldown:
          default-days: 7

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          babel:
              patterns:
                  - '@babel/*'
                  - 'babel-loader'
              update-types: ['minor', 'patch']
          vue:
              patterns:
                  - 'vue'
                  - 'vue-loader'
                  - '@vue/*'
              update-types: ['minor', 'patch']
          react:
              patterns:
                  - 'react'
                  - 'react-dom'
              update-types: ['minor', 'patch']
          preact:
              patterns:
                  - 'preact'
                  - 'preact-compat'
              update-types: ['minor', 'patch']
          svelte:
              patterns:
                  - 'svelte'
                  - 'svelte-loader'
              update-types: ['minor', 'patch']
          sass:
              patterns:
                  - 'sass'
                  - 'sass-loader'
              update-types: ['minor', 'patch']
          less:
              patterns:
                  - 'less'
                  - 'less-loader'
              update-types: ['minor', 'patch']
          stylus:
              patterns:
                  - 'stylus'
                  - 'stylus-loader'
              update-types: ['minor', 'patch']
          postcss:
              patterns:
                  - 'postcss'
                  - 'postcss-loader'
                  - 'autoprefixer'
              update-types: ['minor', 'patch']
          typescript:
              patterns:
                  - 'typescript'
                  - 'ts-loader'
                  - 'fork-ts-checker-webpack-plugin'
              update-types: ['minor', 'patch']
          handlebars:
              patterns:
                  - 'handlebars'
                  - 'handlebars-loader'
              update-types: ['minor', 'patch']
      cooldown:
          default-days: 7
