name: Oxfmt
on: [push, pull_request]

jobs:
    oxfmt:
        name: Oxfmt
        runs-on: ubuntu-latest
        env:
            # We don't want Puppeteer to automatically download a browser when dependencies are being installed
            PUPPETEER_SKIP_DOWNLOAD: 'true'

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v5

            - name: Node ${{matrix.node-versions}}
              uses: actions/setup-node@v4
              with:
                  node-version: '22.13.0'
                  cache: pnpm

            - name: Install pnpm Dependencies
              run: pnpm install

            - name: Run Oxfmt
              run: pnpm fmt:check
