name: Low Dependencies
on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    locked:
        name: Node ${{ matrix.node-versions }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                node-versions: ['22.13.0', '22', '24']
                include:
                    - node-versions: '22.13.0'
                      os: windows-latest
                    - node-versions: '24'
                      os: windows-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install pnpm
                uses: pnpm/action-setup@v5

            -   name: Node ${{matrix.node-versions}}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{matrix.node-versions}}
                    cache: pnpm

            -   name: Remove Lock File
                run: rm pnpm-lock.yaml

            -   name: Force Lowest Dependencies
                run: node ./scripts/force-lowest-dependencies

            # We have some tests that need to "git checkout" package.json file.
            # Commit them prevent the tests from re-using the locked dependencies.
            -   name: Commit Changes, to preserve a clean working directory
                run: |
                    git config --global user.email ""
                    git config --global user.name "Symfony"
                    git commit -am "Force Lowest Dependencies"

            -   name: Install Node.js Dependencies
                run: pnpm install

            -   name: Show Installed Versions
                run: pnpm list --depth=0

            -   name: Run Tests
                run: pnpm test
