name: Locked Dependencies
on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    locked:
        name: Node ${{ matrix.node-versions }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-versions: ['18', '20', '22', '23']

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Node ${{matrix.node-versions}}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{matrix.node-versions}}

            -   name: Install Yarn Dependencies
                run: yarn install

            -   name: Show Installed Versions
                run: yarn list --depth=0

            -   name: Run Tests
                run: yarn test
