name: Testing in real apps
on: [push, pull_request]

jobs:
    testing_app:
        strategy:
            fail-fast: false
            matrix:
                app:
                    - name: npm
                      pkg_manager: npm
                      working_directory: test_apps/npm
                      script: |
                          npm install --ci
                          npm add --save-dev ../../webpack-encore.tgz
                          npm run encore dev
                          npm run encore production

                    - name: npm (with .mjs config)
                      pkg_manager: npm
                      working_directory: test_apps/npm-mjs
                      script: |
                          npm install --ci
                          npm add --save-dev ../../webpack-encore.tgz
                          npm run encore dev
                          npm run encore production

                    - name: npm (with Babel)
                      pkg_manager: npm
                      working_directory: test_apps/npm-with-babel
                      script: |
                          npm install --ci
                          npm add --save-dev ../../webpack-encore.tgz
                          npm run encore dev
                          npm run encore production

                    - name: npm (with external Babel configuration file)
                      pkg_manager: npm
                      working_directory: test_apps/npm-with-external-babel-config
                      script: |
                          npm install --ci
                          npm add --save-dev ../../webpack-encore.tgz
                          npm run encore dev
                          npm run encore production

                    - name: pnpm
                      pkg_manager: pnpm
                      working_directory: test_apps/pnpm
                      script: |
                          pnpm install --frozen-lockfile
                          pnpm add --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: pnpm (with .mjs config)
                      pkg_manager: pnpm
                      working_directory: test_apps/pnpm-mjs
                      script: |
                          pnpm install --frozen-lockfile
                          pnpm add --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: pnpm (with Babel)
                      pkg_manager: pnpm
                      working_directory: test_apps/pnpm-with-babel
                      script: |
                          pnpm install --frozen-lockfile
                          pnpm add --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: pnpm (with external Babel configuration file)
                      pkg_manager: pnpm
                      working_directory: test_apps/pnpm-with-external-babel-config
                      script: |
                          pnpm install --frozen-lockfile
                          pnpm add --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: Yarn Plug'n'Play
                      pkg_manager: yarn
                      working_directory: test_apps/yarn-pnp
                      script: |
                          yarn set version 4.3.0
                          yarn install --immutable
                          yarn add --dev ../../webpack-encore.tgz
                          yarn run encore dev
                          yarn run encore production

                    - name: Yarn Plug'n'Play (with .mjs config)
                      pkg_manager: yarn
                      working_directory: test_apps/yarn-pnp-mjs
                      script: |
                          yarn set version 4.3.0
                          yarn install --immutable
                          yarn add --dev ../../webpack-encore.tgz
                          yarn run encore dev
                          yarn run encore production

                    - name: Yarn Plug'n'Play (with Babel)
                      pkg_manager: yarn
                      working_directory: test_apps/yarn-pnp-with-babel
                      script: |
                          yarn set version 4.3.0
                          yarn install --immutable
                          yarn add --dev ../../webpack-encore.tgz
                          yarn run encore dev
                          yarn run encore production

                    - name: Yarn Plug'n'Play (with external Babel configuration file)
                      pkg_manager: yarn
                      working_directory: test_apps/yarn-pnp-with-external-babel-config
                      script: |
                          yarn set version 4.3.0
                          yarn install --immutable
                          yarn add --dev ../../webpack-encore.tgz
                          yarn run encore dev
                          yarn run encore production

                    - name: lowest peers (sass)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-sass
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (less)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-less
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (postcss)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-postcss
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (react)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-react
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (vue)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-vue
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (vue with JSX)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-vue-jsx
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (TypeScript 5 with Babel preset)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-typescript5
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (TypeScript + fork-ts-checker v7)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-typescript-fork7
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (TypeScript + fork-ts-checker v8)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-typescript-fork8
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (TypeScript + fork-ts-checker v9)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-typescript-fork9
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (Svelte v3)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-svelte3
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (Svelte v4)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-svelte4
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (Stimulus Bridge v3)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-stimulus3
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

                    - name: lowest peers (webpack-cli v6)
                      pkg_manager: pnpm
                      working_directory: test_apps/lowest-peers-webpack-cli6
                      script: |
                          pnpm install --ignore-workspace --frozen-lockfile
                          pnpm add --ignore-workspace --save-dev ../../webpack-encore.tgz
                          pnpm run encore dev
                          pnpm run encore production

        name: ${{ matrix.app.name }}
        runs-on: ubuntu-latest
        permissions: {}
        env:
            # We don't want Puppeteer to automatically download a browser when dependencies are being installed
            PUPPETEER_SKIP_DOWNLOAD: 'true'

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
              with:
                  persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271

            - name: Compute testing app's lockfile
              run: echo "LOCKFILE=${{ matrix.app.pkg_manager == 'yarn' && 'yarn.lock' || matrix.app.pkg_manager == 'pnpm' && 'pnpm-lock.yaml' || matrix.app.pkg_manager == 'npm' && 'package-lock.json' }}" >> $GITHUB_ENV

            - name: Node ${{matrix.node-versions}}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
              with:
                  node-version: '22.13.0'
                  cache: ${{ matrix.app.pkg_manager }}
                  cache-dependency-path: ${{ matrix.app.working_directory }}/${{ env.LOCKFILE }}

            - name: Packing Encore
              run: pnpm pack --out webpack-encore.tgz

            - name: Running script
              working-directory: ${{ matrix.app.working_directory }}
              run: ${{ matrix.app.script }}
