name: Tests
on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    test:
        name: Node ${{ matrix.node-versions }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        permissions: {}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                node-versions: ['22.18.0', '22', '24', '26']
                include:
                    - node-versions: '22.18.0'
                      os: windows-latest
                    - node-versions: '24'
                      os: windows-latest
                    - node-versions: '26'
                      os: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

            - name: Node ${{matrix.node-versions}}
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: ${{matrix.node-versions}}
                  cache: pnpm

            - name: Install Node.js Dependencies
              run: pnpm install

            - name: Show Installed Versions
              run: pnpm list --depth=0

            - name: Install Puppeteer Browsers
              run: npx puppeteer browsers install chrome

            - name: Run Tests
              run: pnpm test
